Fix typechecking
EncodedVenom/ZoneDaemon pull request #4
Opened 2022-03-20 23:05 UTC by LuaRook

Fixed typechecking

2022-03-20 23:11 UTC, EncodedVenom requested changes

2022-03-20 23:11 UTC, EncodedVenom commented on src/ZoneDaemon/init.lua
Variables that have their definition at declaration shouldn't be typed as it can be inferred quite reliably.

2022-03-20 23:11 UTC, EncodedVenom commented on src/ZoneDaemon/init.lua
> +local function isValidContainer(container: Array<BasePart> | Instance): BasePart | Array<BasePart>
I don't know how well roblox studio handles Array<T> types instead of {T} types. Worth investigating.

2022-03-20 23:11 UTC, EncodedVenom commented on src/ZoneDaemon/init.lua
> +	local listOfParts: Array<BasePart> = isValidContainer(container)
Unnecessary type as isValidContainer has a strict return type.

2022-03-20 23:11 UTC, EncodedVenom commented on src/ZoneDaemon/init.lua
> +	local container: Model = Instance.new("Model")
Unnecessary type.

2022-03-21 00:57 UTC, LuaRook commented on src/ZoneDaemon/init.lua
> +	local container: Model = Instance.new("Model")
I have to put this in a separate commit as I forgot to do this.

2022-03-21 23:09 UTC, EncodedVenom approved these changes
LGTM as of writing. お疲れ様でした！

2022-03-21 23:09 UTC, merged